import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

# Configure your email credentials
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
EMAIL_SENDER = "georgefredrick345@gmail.com"  # Replace with your email
EMAIL_PASSWORD = "your_password"  # Replace with your app password (not regular password)

def send_report(receiver_email, report_files):
    try:
        # Setup the email message
        msg = MIMEMultipart()
        msg['From'] = EMAIL_SENDER
        msg['To'] = receiver_email
        msg['Subject'] = "Darkseid OSINT Report"

        # Email body
        body = "Attached are the OSINT reports generated by Darkseid."
        msg.attach(MIMEText(body, 'plain'))

        # Attach PDF reports
        for report_file in report_files:
            if os.path.exists(report_file):
                attachment = open(report_file, "rb")
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(attachment.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f"attachment; filename={os.path.basename(report_file)}")
                msg.attach(part)
                attachment.close()

        # Connect to SMTP server and send email
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        server.sendmail(EMAIL_SENDER, receiver_email, msg.as_string())
        server.quit()

        print(f"📧 Report successfully sent to {receiver_email}")

    except Exception as e:
        print(f"❌ Email sending failed: {str(e)}")
